server {
    listen 80;
    server_name bytebuddies.technology www.bytebuddies.technology;
    root /home/ubuntu/bytebuddies;
    index index.html;
    location / {
        try_files $uri /index.html;
    }
}
server {
    listen 443 ssl;
    server_name bytebuddies.technology www.bytebuddies.technology;
    ssl_certificate /etc/letsencrypt/live/bytebuddies.technology/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bytebuddies.technology/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    root /home/ubuntu/bytebuddies;
    index index.html;
    location / {
        try_files $uri /index.html;
    }
}
