/**
 * Generates src/data/lessonCatalog.js and rebuilds course export.
 * Run: node scripts/generateLessonCourses.mjs
 */
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const YEARS = [
  {
    year: 3, ages: '8–9', defaultDifficulty: 'Beginner',
    categories: [
      ['y3-block-coding', 'Block Coding Fundamentals', '🧩', '#6366f1', [
        ['Welcome to Block Coding', 'Introduction to visual programming'],
        ['Meet the Blocks', 'Learn the basic block types'],
        ['Events: The "When" Block', 'Triggering actions'],
        ['Sequences: Do Things in Order', 'Understanding order matters'],
        ['Make Your Sprite Talk', 'Speech bubbles and communication'],
        ['Move Your Sprite', 'Basic movement commands'],
        ['Turn and Rotate', 'Changing sprite direction'],
        ['Wait for It...', 'Introduction to timing'],
        ['Repeat Block Magic', 'Simple loops (repeat 3 times)'],
        ['Forever Loops', 'Continuous repetition'],
        ['Colors & Costumes', 'Changing sprite appearance'],
        ['Sound Effects', 'Adding audio to your code'],
        ['If This, Then That', 'Basic conditionals'],
        ['Touching the Edge', 'Boundary detection'],
        ['Size Changes', 'Growing and shrinking sprites'],
        ['Opacity & Visibility', 'Show/hide and transparency'],
        ['Your First Mini-Game', 'Combining blocks'],
        ['Mystery Challenge', 'Problem-solving with blocks'],
      ]],
      ['y3-pixel-art', 'Pixel Art & Digital Design', '🎨', '#ec4899', [
        ['Pixel Art Basics', 'Creating pixel graphics'],
        ['Color Palettes', 'Choosing colors that work together'],
        ['Symmetry & Patterns', 'Creating balanced designs'],
        ['Sprite Design Workshop', 'Design your own character'],
        ['Animated Sprites', 'Making sprites move and change'],
        ['Backgrounds & Scenes', 'Creating environments'],
        ['Pixel Animation Flip Book', 'Frame-by-frame animation'],
        ['Retro Game Graphics', 'Classic pixel style'],
        ['Emoji-Inspired Art', 'Using simple shapes'],
        ['Nature in Pixels', 'Animals, plants, landscapes'],
        ['Character Customization', 'Creating character variations'],
        ['Pixel Art Gallery', 'Showcase and share'],
      ]],
      ['y3-storytelling', 'Storytelling & Narrative', '📖', '#8b5cf6', [
        ['Your First Story', 'Narrative with code'],
        ['Characters Come to Life', 'Creating believable sprites'],
        ['Dialogue & Conversation', 'Making sprites talk'],
        ['Setting the Scene', 'Backgrounds and environments'],
        ['Plot Twist!', 'Adding unexpected events'],
        ['Adventure Quest', 'Building a simple story game'],
        ['Mystery Story', 'Creating suspense'],
        ['Time Travel Tale', 'Non-linear storytelling'],
        ['Choose Your Adventure', 'Branching narratives'],
        ['Publish Your Story', 'Sharing your creation'],
      ]],
      ['y3-music', 'Music & Rhythm Coding', '🎵', '#f59e0b', [
        ['Sound Effects 101', 'Making beeps and boops'],
        ['Build a Drum Kit', 'Coding percussion'],
        ['Melodies & Notes', 'Creating simple songs'],
        ['Rhythm Master', 'Timing and beats'],
        ['Musical Loops', 'Repeating patterns'],
        ['Create a Jingle', 'Short, catchy songs'],
        ["Conductor's Baton", 'Control music with code'],
        ['Sound Story', 'Combining music and narrative'],
      ]],
      ['y3-math', 'Math & Logic Games', '🔢', '#10b981', [
        ['Number Ninja', 'Quick math challenges'],
        ['Addition Quest', 'Math in a game setting'],
        ['Subtraction Safari', 'Math adventure'],
        ['Multiplication Master', 'Multiplying numbers'],
        ['Division Detective', 'Breaking numbers apart'],
        ['Counting Challenges', 'Logic and sequences'],
        ['Pattern Recognition', 'Finding mathematical patterns'],
        ['Shapes & Numbers', 'Geometry basics'],
      ]],
      ['y3-animals', 'Animals & Nature', '🦊', '#22c55e', [
        ['Creature Creator', 'Design fantasy animals'],
        ['Virtual Pet', 'Care for a digital creature'],
        ['Nature Animator', 'Animate nature scenes'],
        ['Ecosystem Simulator', 'Simple predator/prey'],
        ['Ocean Explorer', 'Underwater creatures'],
        ['Forest Friends', 'Woodland animal coding'],
      ]],
      ['y3-sports', 'Movement & Sports', '⚽', '#3b82f6', [
        ['Dance Moves', 'Make sprites dance'],
        ['Soccer Simulator', 'Basic sports game'],
        ['Racing Game', 'Simple car racing'],
        ['Jump & Hop', 'Platformer basics'],
        ['Swimming Sprite', 'Fluid movement'],
        ['Sports Skills Challenge', 'Athletic mini-games'],
      ]],
    ],
  },
  {
    year: 4, ages: '9–10', defaultDifficulty: 'Beginner',
    categories: [
      ['y4-game-dev', 'Game Development Foundations', '🎮', '#ec4899', [
        ['Game Design Basics', 'Elements of good games'],
        ['Player Movement', 'Smooth character control'],
        ['Enemy Behavior', 'Simple AI enemies'],
        ['Collision Detection', 'Objects touching'],
        ['Score System', 'Tracking points'],
        ['Lives & Health', 'Managing game state'],
        ['Power-Ups & Bonuses', 'Special items'],
        ['Levels & Progression', 'Multiple game stages'],
        ['Game Over & Win States', 'Ending conditions'],
        ['Sound Design for Games', 'Audio effects'],
        ['Background Scrolling', 'Moving environments'],
        ['Random Events', 'Unpredictable gameplay'],
        ['Difficulty Settings', 'Adjusting challenge'],
        ['Save & Load', 'Game progress tracking'],
        ['Tutorial Design', 'Teaching players'],
        ['Boss Battle', 'Final challenge design'],
        ['Mini-Game Collection', 'Multiple games'],
        ['Leaderboard System', 'Competitive play'],
        ['Game Polishing', 'Making it feel great'],
        ['Publish Your Game', 'Sharing your creation'],
      ]],
      ['y4-variables', 'Variables & Data Storage', '📦', '#6366f1', [
        ['What are Variables?', 'Storing information'],
        ['Number Variables', 'Working with numbers'],
        ['Text Variables', 'Storing words'],
        ['Boolean Variables', 'True or false'],
        ['Lists & Arrays', 'Storing collections'],
        ['Variable Operations', 'Math with variables'],
        ['Counters & Scores', 'Tracking values'],
        ['Lives & Health Systems', 'Game state'],
        ['Timers & Clocks', 'Tracking time'],
        ['Global vs Local', 'Variable scope'],
        ['String Manipulation', 'Text operations'],
        ['Data Challenge', 'Complex variable usage'],
      ]],
      ['y4-conditionals', 'Conditional Logic', '🔀', '#8b5cf6', [
        ['If Statements Explained', 'Making decisions'],
        ['If-Else Basics', 'Two paths forward'],
        ['Multiple Conditions', 'Using AND/OR'],
        ['Nested If Statements', 'Conditions within conditions'],
        ['Comparing Numbers', 'Greater than, less than'],
        ['Comparing Texts', 'String comparisons'],
        ['Loops with Conditions', 'Conditional repetition'],
        ['Game Logic', 'Using conditions in games'],
        ['Quiz Game', 'Conditional questions'],
        ['State Machines', 'Managing modes'],
        ['Error Checking', 'Preventing problems'],
        ['Logic Puzzle Master', 'Complex conditions'],
      ]],
      ['y4-game-design', 'Intermediate Game Design', '🕹️', '#f59e0b', [
        ['Maze Generator', 'Create challenging mazes'],
        ['Treasure Hunt', 'Finding hidden items'],
        ['Catch the Falling Objects', 'Arcade-style game'],
        ['Breakout/Brick Game', 'Ball and paddle'],
        ['Space Shooter', 'Shooting enemies'],
        ['Platformer Adventure', 'Jumping and obstacles'],
        ['Puzzle Game', 'Logic-based gameplay'],
        ['Card Game', 'Turn-based strategy'],
        ['Multiplayer Basics', 'Two-player games'],
        ['Game Jam Challenge', 'Create in limited time'],
      ]],
      ['y4-web', 'Web Basics', '🌐', '#06b6d4', [
        ['What is the Internet?', 'How the web works'],
        ['HTML Structure', 'Building web pages'],
        ['Tags & Elements', 'HTML building blocks'],
        ['Text Formatting', 'Bold, italic, headers'],
        ['Adding Images', 'Embedding pictures'],
        ['Links & Navigation', 'Connecting pages'],
        ['Your First Webpage', 'Complete HTML page'],
        ['Webpages in the Wild', 'Analyzing real sites'],
      ]],
      ['y4-cyber', 'Cybersecurity Basics', '🔒', '#ef4444', [
        ['What is Cybersecurity?', 'Protection from threats'],
        ['Password Power', 'Creating strong passwords'],
        ['Phishing Explained', 'Recognizing scams'],
        ['Safe Browsing', 'Protecting yourself online'],
        ['Privacy Settings', 'Controlling your data'],
        ['Two-Factor Authentication', 'Extra protection'],
        ['Digital Citizenship', 'Online behavior'],
        ['Cybersecurity Challenge', 'Test your knowledge'],
      ]],
      ['y4-algorithms', 'Algorithms & Problem Solving', '🧠', '#10b981', [
        ['What is an Algorithm?', 'Step-by-step instructions'],
        ['Sorting Basics', 'Organizing data'],
        ['Bubble Sort', 'Simple sorting algorithm'],
        ['Selection Sort', 'Another sorting method'],
        ['Searching Algorithms', 'Finding information'],
        ['Linear Search', 'Step-by-step searching'],
        ['Binary Search', 'Efficient searching'],
        ['Pathfinding Basics', 'Finding routes'],
        ['Optimization', 'Making code better'],
        ['Algorithm Race', 'Comparing efficiency'],
      ]],
      ['y4-ai', 'Artificial Intelligence Basics', '🤖', '#a855f7', [
        ['What is AI?', 'Introduction to artificial intelligence'],
        ['Machine Learning Basics', 'Computers learning'],
        ['Training a Model', 'Teaching AI'],
        ['Pattern Recognition', 'Finding patterns'],
        ['Prediction Games', 'Forecasting outcomes'],
        ['Simple Chatbot', 'Conversational AI'],
        ['AI Ethics', 'Responsible AI use'],
        ['AI in the Real World', 'Applications of AI'],
      ]],
    ],
  },
  {
    year: 5, ages: '10–11', defaultDifficulty: 'Intermediate',
    categories: [
      ['y5-python', 'Python Programming', '🐍', '#10b981', [
        ['Python Basics', 'Introduction to text coding'],
        ['Variables in Python', 'Storing data'],
        ['Data Types', 'Numbers, strings, booleans'],
        ['Print Function', 'Displaying output'],
        ['Input Function', 'Getting user input'],
        ['Arithmetic Operations', 'Math in Python'],
        ['String Operations', 'Text manipulation'],
        ['If Statements in Python', 'Making decisions'],
        ['If-Else-Elif', 'Multiple conditions'],
        ['Loops: For Loops', 'Repeating code'],
        ['Loops: While Loops', 'Conditional repetition'],
        ['Loop Control', 'Break and continue'],
        ['Lists in Python', 'Storing collections'],
        ['List Operations', 'Working with lists'],
        ['Dictionaries', 'Key-value pairs'],
        ['Functions', 'Reusable code blocks'],
        ['Function Parameters', 'Passing information'],
        ['Return Values', 'Getting results back'],
        ['Comments & Documentation', 'Explaining code'],
        ['Python Challenge Projects', 'Real-world problems'],
      ]],
      ['y5-web', 'Advanced Web Development', '💻', '#06b6d4', [
        ['CSS Styling', 'Making websites look good'],
        ['Colors & Fonts', 'Visual design'],
        ['Layout with CSS', 'Positioning elements'],
        ['Flexbox', 'Modern layouts'],
        ['Grid System', 'Advanced layouts'],
        ['Responsive Design', 'Mobile-friendly sites'],
        ['Buttons & Interactions', 'User interaction'],
        ['Forms & Input', 'Collecting data'],
        ['JavaScript Basics', 'Adding interactivity'],
        ['Event Handlers', 'Responding to clicks'],
        ['DOM Manipulation', 'Changing web pages'],
        ['Simple Website', 'Complete project'],
        ['Personal Portfolio', 'Showcase your work'],
        ['Blog Layout', 'Content-heavy site'],
        ['Publish Your Website', 'Going live'],
      ]],
      ['y5-data-structures', 'Data Structures', '🗂️', '#6366f1', [
        ['Arrays & Lists', 'Sequential data'],
        ['Stacks', 'Last in, first out'],
        ['Queues', 'First in, first out'],
        ['Linked Lists', 'Connected data'],
        ['Trees', 'Hierarchical data'],
        ['Graphs', 'Complex relationships'],
        ['Hash Tables', 'Fast lookups'],
        ['Sets', 'Unique values'],
        ['Tuples', 'Immutable sequences'],
        ['Choosing Data Structures', 'Best practices'],
        ['Data Structure Efficiency', 'Time & space'],
        ['Data Structure Projects', 'Real applications'],
      ]],
      ['y5-algorithms', 'Advanced Algorithms', '⚡', '#f59e0b', [
        ['Recursion', 'Functions calling themselves'],
        ['Divide and Conquer', 'Breaking down problems'],
        ['Merge Sort', 'Efficient sorting'],
        ['Quick Sort', 'Fast sorting algorithm'],
        ['Binary Search Tree', 'Organized data'],
        ['Graph Traversal', 'Exploring connections'],
        ['Breadth-First Search', 'Level-by-level search'],
        ['Depth-First Search', 'Deep exploration'],
        ['Dynamic Programming', 'Optimization technique'],
        ['Greedy Algorithms', 'Making best choices'],
        ['Algorithm Complexity', 'Big O notation'],
        ['Algorithm Design Challenge', 'Create your own'],
      ]],
      ['y5-databases', 'Database Concepts', '🗄️', '#8b5cf6', [
        ['What is a Database?', 'Data storage'],
        ['SQL Basics', 'Database language'],
        ['SELECT Statements', 'Retrieving data'],
        ['WHERE Clauses', 'Filtering data'],
        ['Joins', 'Combining tables'],
        ['INSERT & UPDATE', 'Modifying data'],
        ['DELETE Operations', 'Removing data'],
        ['Database Design', 'Planning databases'],
        ['Queries & Reports', 'Extracting information'],
        ['Build a Simple Database', 'Practical project'],
      ]],
      ['y5-cyber', 'Cybersecurity Advanced', '🛡️', '#ef4444', [
        ['Encryption Explained', 'Securing information'],
        ['Caesar Cipher', 'Historical encryption'],
        ['Modern Encryption', 'Current methods'],
        ['Hashing', 'One-way encryption'],
        ['Authentication', 'Proving identity'],
        ['Authorization', 'Controlling access'],
        ['Common Vulnerabilities', 'SQL injection, XSS'],
        ['Secure Coding', 'Writing safe code'],
        ['Penetration Testing', 'Finding weaknesses'],
        ['Cybersecurity Career', 'Jobs in the field'],
      ]],
      ['y5-game-advanced', 'Game Development Advanced', '🎯', '#ec4899', [
        ['Game Engines', 'Intro to Unity/Godot'],
        ['2D Game Physics', 'Gravity and collision'],
        ['Particle Effects', 'Visual polish'],
        ['Animation Systems', 'Smooth movement'],
        ['State Management', 'Organizing game states'],
        ['Network Play', 'Multiplayer fundamentals'],
        ['Game Monetization', 'Making money'],
        ['User Experience', 'Making games fun'],
        ['Performance Optimization', 'Smooth gameplay'],
        ['Professional Game Development', 'Industry insights'],
      ]],
      ['y5-ml', 'Machine Learning Basics', '📊', '#a855f7', [
        ['Supervised Learning', 'Learning from examples'],
        ['Classification', 'Categorizing data'],
        ['Regression', 'Predicting values'],
        ['Unsupervised Learning', 'Finding patterns'],
        ['Clustering', 'Grouping similar items'],
        ['Neural Networks', 'Brain-inspired learning'],
        ['Training & Testing', 'Validating models'],
        ['Overfitting & Underfitting', 'Common problems'],
        ['Real-World ML', 'Applications'],
        ['Build Your Own ML Model', 'Practical project'],
      ]],
    ],
  },
  {
    year: 6, ages: '11–12', defaultDifficulty: 'Advanced',
    categories: [
      ['y6-python', 'Advanced Python', '🐍', '#10b981', [
        ['Object-Oriented Programming', 'Classes and objects'],
        ['Classes & Objects', 'Creating custom types'],
        ['Constructors & Initialization', 'Setting up objects'],
        ['Methods', 'Functions in classes'],
        ['Attributes', 'Object properties'],
        ['Inheritance', 'Extending classes'],
        ['Polymorphism', 'Different behavior, same interface'],
        ['Encapsulation', 'Hiding implementation'],
        ['Static Methods', 'Class-level functions'],
        ['Decorators', 'Modifying functions'],
        ['File I/O', 'Reading and writing files'],
        ['Error Handling', 'Try-except blocks'],
        ['Debugging', 'Finding and fixing bugs'],
        ['Testing', 'Writing test code'],
        ['Libraries & Imports', 'Using external code'],
        ['Regular Expressions', 'Pattern matching'],
        ['Asynchronous Programming', 'Concurrent code'],
        ['Advanced Python Project', 'Complex application'],
      ]],
      ['y6-web-pro', 'Web Development Pro', '🌐', '#06b6d4', [
        ['Backend Basics', 'Server-side code'],
        ['APIs', 'Application programming interfaces'],
        ['REST APIs', 'Building web services'],
        ['JSON Data', 'Structured data format'],
        ['Fetch API', 'Getting data from servers'],
        ['Cookies & Sessions', 'Tracking users'],
        ['Authentication', 'User login systems'],
        ['Databases in Web Apps', 'Backend storage'],
        ['Server Setup', 'Hosting your app'],
        ['Performance Tuning', 'Fast websites'],
        ['SEO Basics', 'Search engine optimization'],
        ['Accessibility', 'Inclusive design'],
        ['Security Best Practices', 'Safe websites'],
        ['Full Stack Project', 'Frontend + Backend'],
        ['Deploy Your App', 'Making it live'],
      ]],
      ['y6-data-structures', 'Advanced Data Structures', '🗂️', '#6366f1', [
        ['B-Trees', 'Balanced search trees'],
        ['Red-Black Trees', 'Self-balancing trees'],
        ['Heaps', 'Priority queues'],
        ['Tries', 'Prefix trees'],
        ['Skip Lists', 'Probabilistic structures'],
        ['Bloom Filters', 'Space-efficient searching'],
        ['Union-Find', 'Grouping elements'],
        ['Segment Trees', 'Range queries'],
        ['Advanced Structures Design', 'Custom data structures'],
        ['Choosing the Right Structure', 'Optimization decisions'],
      ]],
      ['y6-algorithms', 'Advanced Algorithms', '⚡', '#f59e0b', [
        ['Network Flow', 'Maximum flow problems'],
        ['Matching Algorithms', 'Pairing elements'],
        ['NP-Complete Problems', 'Hard problems'],
        ['Approximation Algorithms', 'Finding good solutions'],
        ['Randomized Algorithms', 'Using randomness'],
        ['Parallel Algorithms', 'Multi-processor computing'],
        ['String Algorithms', 'Text processing'],
        ['Computational Geometry', 'Spatial problems'],
        ['Game Theory', 'Strategic algorithms'],
        ['Algorithm Verification', 'Proving correctness'],
        ['Competitive Programming', 'Algorithm contests'],
        ['Algorithm Research', 'Cutting-edge techniques'],
      ]],
      ['y6-databases', 'Databases Advanced', '🗄️', '#8b5cf6', [
        ['Relational Databases', 'Table-based data'],
        ['NoSQL Databases', 'Alternative storage'],
        ['Database Normalization', 'Efficient design'],
        ['Indexes', 'Fast lookups'],
        ['Transactions', 'Data integrity'],
        ['Query Optimization', 'Fast queries'],
        ['Database Security', 'Protecting data'],
        ['Backup & Recovery', 'Data safety'],
        ['Scaling Databases', 'Growing systems'],
        ['Database Administration', 'Maintaining databases'],
      ]],
      ['y6-cyber-pro', 'Cybersecurity Professional', '🛡️', '#ef4444', [
        ['Network Security', 'Protecting networks'],
        ['Firewalls', 'Blocking threats'],
        ['VPNs', 'Private networks'],
        ['SSL/TLS', 'Secure communication'],
        ['Intrusion Detection', 'Finding attackers'],
        ['Malware Analysis', 'Understanding threats'],
        ['Incident Response', 'Handling breaches'],
        ['Penetration Testing', 'Authorized hacking'],
        ['Security Compliance', 'Following standards'],
        ['Risk Assessment', 'Evaluating threats'],
        ['Cryptography Advanced', 'Deep dive'],
        ['Cybersecurity Careers', 'Specializations'],
      ]],
      ['y6-ai-advanced', 'Artificial Intelligence Advanced', '🤖', '#a855f7', [
        ['Deep Learning', 'Advanced neural networks'],
        ['Convolutional Networks', 'Image AI'],
        ['Recurrent Networks', 'Sequential data'],
        ['Natural Language Processing', 'Understanding text'],
        ['Computer Vision', 'Image understanding'],
        ['Reinforcement Learning', 'Learning by reward'],
        ['Generative Models', 'Creating new data'],
        ['Transfer Learning', 'Reusing models'],
        ['Model Explainability', 'Understanding AI'],
        ['AI in Industry', 'Real-world applications'],
        ['AI Safety & Ethics', 'Responsible development'],
        ['Build an AI System', 'Complete project'],
      ]],
      ['y6-mobile', 'Mobile App Development', '📱', '#ec4899', [
        ['Mobile Development Basics', 'Phone apps'],
        ['iOS Development', 'Apple apps'],
        ['Android Development', 'Google apps'],
        ['Cross-Platform Development', 'One code, many devices'],
        ['Mobile UI Design', 'Small screen design'],
        ['Touch Interactions', 'Phone-specific input'],
        ['Mobile Performance', 'Battery & speed'],
        ['App Distribution', 'Publishing apps'],
        ['Mobile Security', 'Protecting users'],
        ['Build Your Own App', 'Complete project'],
      ]],
      ['y6-cloud', 'Cloud Computing & DevOps', '☁️', '#3b82f6', [
        ['Cloud Computing Basics', 'Computing on demand'],
        ['AWS', 'Amazon cloud services'],
        ['Azure', 'Microsoft cloud'],
        ['Google Cloud', 'Google services'],
        ['Containers & Docker', 'Portable applications'],
        ['Kubernetes', 'Container orchestration'],
        ['Continuous Integration', 'Automated testing'],
        ['Continuous Deployment', 'Automated releases'],
        ['Infrastructure as Code', 'Programming infrastructure'],
        ['Cloud Architecture', 'Designing systems'],
      ]],
      ['y6-git', 'Version Control & Collaboration', '🔧', '#64748b', [
        ['Git Basics', 'Version control system'],
        ['Commits & History', 'Tracking changes'],
        ['Branches', 'Parallel development'],
        ['Merging', 'Combining work'],
        ['GitHub/GitLab', 'Collaborative platforms'],
        ['Pull Requests', 'Code review'],
        ['Collaboration Workflows', 'Team development'],
        ['Open Source Contributing', 'Community projects'],
      ]],
      ['y6-game-pro', 'Game Development Professional', '🎮', '#f97316', [
        ['Game Development Pipelines', 'Development process'],
        ['Advanced Physics', 'Realistic movement'],
        ['Procedural Generation', 'Creating content with code'],
        ['Networking & Multiplayer', 'Online games'],
        ['Graphics Programming', 'Visual effects'],
        ['Audio Programming', 'Professional sound'],
        ['Game Optimization', 'Maximum performance'],
        ['Game Publishing', 'Releasing games'],
        ['Game Business', 'Monetization strategies'],
        ['Create a Professional Game', 'Advanced project'],
      ]],
      ['y6-capstone', 'Capstone Projects', '🏆', '#eab308', [
        ['Capstone Project Planning', 'Design phase'],
        ['Full-Stack Application', 'Complete project'],
        ['Advanced Game', 'Professional game'],
        ['AI Application', 'Machine learning project'],
        ['Open Source Contribution', 'Community work'],
        ['Portfolio Presentation', 'Showcasing work'],
      ]],
      ['y6-careers', 'CS Careers & Soft Skills', '💼', '#14b8a6', [
        ['Tech Industry Overview', 'Career landscape'],
        ['Software Engineering Roles', 'Job types'],
        ['Interview Preparation', 'Getting hired'],
        ['Technical Writing', 'Documenting code'],
        ['Teamwork & Leadership', 'Soft skills'],
        ['Continuous Learning', 'Staying updated'],
        ['Networking & Mentorship', 'Building connections'],
        ['Ethics in Computing', 'Responsible tech'],
      ]],
      ['y6-competitive', 'Competitive Programming', '🏁', '#ef4444', [
        ['Codeforces Basics', 'Online contests'],
        ['Competitive Strategies', 'Problem-solving speed'],
        ['Common Problem Types', 'Contest patterns'],
        ['Optimization Tricks', 'Fast solutions'],
        ['Contest Preparation', 'Training methods'],
        ['Your First Competition', 'Getting started'],
      ]],
      ['y6-blockchain', 'Blockchain & Crypto', '⛓️', '#f59e0b', [
        ['Blockchain Basics', 'Distributed ledgers'],
        ['Bitcoin & Cryptocurrency', 'Digital money'],
        ['Smart Contracts', 'Programmable agreements'],
        ['Ethereum', 'The smart contract platform'],
        ['DeFi (Decentralized Finance)', 'Financial services'],
        ['Blockchain Applications', 'Real-world uses'],
      ]],
      ['y6-arvr', 'AR/VR Development', '🥽', '#8b5cf6', [
        ['Virtual Reality Basics', 'Immersive worlds'],
        ['Augmented Reality', 'Real world overlays'],
        ['VR Development Tools', 'Building VR'],
        ['AR Development Tools', 'Building AR'],
        ['Designing for VR/AR', 'Unique considerations'],
        ['Create Your Own Experience', 'VR/AR project'],
      ]],
      ['y6-robotics', 'Robotics & IoT', '🤖', '#22c55e', [
        ['Robotics Basics', 'Robots and automation'],
        ['Arduino Programming', 'Microcontroller coding'],
        ['Sensors & Actuators', 'Robot components'],
        ['Internet of Things', 'Connected devices'],
        ['Smart Home', 'Automated homes'],
        ['Robot Design', 'Building robots'],
        ['Autonomous Systems', 'Self-driving basics'],
        ['Robotics Challenge', 'Build and program'],
      ]],
      ['y6-sound', 'Sound & Music Programming', '🎧', '#ec4899', [
        ['Digital Audio Basics', 'How sound works'],
        ['Audio Processing', 'Manipulating sound'],
        ['Music Generation', 'Creating music with code'],
        ['MIDI Programming', 'Musical instructions'],
        ['Sound Synthesis', 'Creating instruments'],
        ['Build a Music App', 'Complete project'],
      ]],
      ['y6-modding', 'Game Mod Development', '🛠️', '#6366f1', [
        ['Game Modding Basics', 'Modifying existing games'],
        ['Minecraft Modding', 'Create Minecraft mods'],
        ['Unreal Engine Modding', 'Modify Unreal games'],
        ['Unity Asset Store', 'Using resources'],
        ['Mod Publishing', 'Sharing your mods'],
        ['Mod Development Community', 'Connecting with others'],
      ]],
      ['y6-chatbots', 'Virtual Assistants & Chatbots', '💬', '#06b6d4', [
        ['Chatbot Basics', 'Conversational AI'],
        ['Natural Language Processing', 'Understanding text'],
        ['Bot Frameworks', 'Building tools'],
        ['Dialogue Management', 'Conversation flow'],
        ['Integration with APIs', 'Connecting services'],
        ['Deploy Your Bot', 'Make it live'],
      ]],
    ],
  },
];

const catalog = YEARS.map((y) => ({
  year: y.year,
  ages: y.ages,
  defaultDifficulty: y.defaultDifficulty,
  categories: y.categories.map(([id, title, icon, color, lessons]) => ({
    id,
    title,
    icon,
    color,
    lessons: lessons.map(([title, blurb]) => ({ title, blurb })),
  })),
}));

const out = `/** Auto-generated lesson catalog — 426+ Code.org-style lessons (Years 3–6). */\nexport const LESSON_CATALOG = ${JSON.stringify(catalog, null, 2)};\n`;
writeFileSync(join(root, 'src/data/lessonCatalog.js'), out);

let total = 0;
catalog.forEach((y) => y.categories.forEach((c) => { total += c.lessons.length; }));
console.log(`Wrote lessonCatalog.js — ${total} lessons across ${catalog.reduce((s, y) => s + y.categories.length, 0)} courses`);
