/**
 * AerialCourseRecipes — data specs for 10 sky_aerial flight courses.
 */
export const AERIAL_ARENA_TYPES = new Set([
  'drone_canyon', 'canyon_flight', 'storm_cloud', 'cloud_race', 'space_orbit',
  'flight_rings', 'jet_stunt', 'rooftop_delivery', 'typhoon', 'warp_gate',
  'rainbow_road', 'sunny_circuit', 'dragon_skyway', 'volcano_drift', 'street_grand_prix',
]);

export const AERIAL_COURSE_RECIPES = {
  drone_canyon: {
    id: 'drone_canyon',
    label: 'Sky Academy',
    difficultyLevel: 1,
    gateColors: { primary: 0x38bdf8, secondary: 0xfacc15, final: 0x22c55e },
    goldenHour: true,
    sky: { top: '#e87830', mid: '#f5a623', horizon: '#ffe8b0', fog: '#e8c090', near: 90, far: 280 },
    vista: { type: 'canyon_floor', y: -42, wallInner: 18 },
    hero: { type: 'sky_academy_arch', t: 0.08 },
    spline: { kind: 'canyon_slalom', length: 185, start: [0, 16, 0], end: [12, 18, -185], yMin: 14, yMax: 22, count: 16 },
    gates: { mode: 'ring', count: 12, tier: 'tutorial' },
    gltfTrack: 'cloud_citadel_01',
    parallaxClouds: true,
    rim: { color: '#ff9040', intensity: 0.4 },
  },
  canyon_flight: {
    id: 'canyon_flight',
    label: 'Altitude Lock',
    difficultyLevel: 2,
    gateColors: { primary: 0x22d3ee, secondary: 0xffa040, final: 0x22c55e },
    goldenHour: true,
    sky: { top: '#3478b8', mid: '#87b9d6', horizon: '#ffd39a', fog: '#d7b78f', near: 125, far: 380 },
    vista: { type: 'cloud_sea', y: -56 },
    hero: { type: 'canyon_citadel', t: 0.48 },
    spline: { kind: 'canyon_slalom', length: 210, start: [0, 26, 0], end: [8, 29, -210], yMin: 24, yMax: 32, count: 18 },
    gates: { mode: 'ring', count: 6, tier: 'standard' },
    gltfTrack: 'cloud_citadel_01',
    parallaxClouds: true,
    rim: { color: '#ffb45c', intensity: 0.3 },
    islandScatter: [
      { t: 0.08, side: -1, off: 34, yOff: -12, hero: true },
      { t: 0.22, side: 1, off: 42, yOff: -18, spire: true, castle: true },
      { t: 0.38, side: -1, off: 48, yOff: -14, hero: true },
      { t: 0.55, side: 1, off: 38, yOff: -11, hero: true },
      { t: 0.7, side: -1, off: 44, yOff: -20, spire: true, castle: true },
      { t: 0.84, side: 1, off: 52, yOff: -15, hero: true },
      { t: 0.94, side: -1, off: 36, yOff: -12, spire: true },
    ],
  },
  storm_cloud: {
    id: 'storm_cloud',
    label: 'Target Dive',
    difficultyLevel: 3,
    gateColors: { primary: 0xa78bfa, secondary: 0xfde047, final: 0xef4444 },
    sky: { top: '#3b4a6b', mid: '#6b7a9a', horizon: '#9aa8c0', fog: '#5a6a8a', near: 60, far: 200 },
    vista: { type: 'farmland_grid', y: -58 },
    hero: { type: 'supercell_wall', t: 0.45 },
    spline: { kind: 'dive_targets', length: 175, start: [0, 38, 0], end: [0, 28, -175], dives: 5 },
    gates: { mode: 'mixed', ringCount: 3, targetCount: 5, tier: 'standard' },
    gltfTrack: 'thunder_ridge_01',
    stormClouds: true,
    rain: true,
  },
  cloud_race: {
    id: 'cloud_race',
    label: 'Cloud Slalom',
    difficultyLevel: 4,
    gateColors: { primary: 0x34d399, secondary: 0xf472b6, final: 0xfacc15 },
    goldenHour: true,
    sky: { top: '#4fc3f7', mid: '#f5a623', horizon: '#ffe8b0', fog: '#e8c090', near: 80, far: 280 },
    vista: { type: 'cloud_sea', y: -48 },
    hero: { type: 'cloud_whale', t: 0.22 },
    spline: { kind: 'figure8', length: 210, centerY: 26, amplitude: 12, count: 20 },
    gates: { mode: 'ring', count: 10, tier: 'standard' },
    gltfTrack: 'cloud_citadel_01',
    parallaxClouds: true,
    cloudPillars: 14,
  },
  space_orbit: {
    id: 'space_orbit',
    label: 'Vertical Ascent',
    difficultyLevel: 5,
    gateColors: { primary: 0x8b5cf6, secondary: 0x22d3ee, final: 0xf472b6 },
    sky: { preset: 'star_station_01', top: '#120428', mid: '#2a1058', horizon: '#3a2080', fog: '#1a0840', near: 80, far: 280 },
    vista: { type: 'launch_pad', y: 0 },
    hero: { type: 'orbital_station', t: 0.95 },
    spline: { kind: 'spiral_climb', length: 130, climb: 70, startY: 8, count: 14 },
    gates: { mode: 'ring', count: 10, tier: 'mixed' },
    gltfTrack: 'star_station_01',
    launchTower: true,
    starfieldAbove: 60,
  },
  flight_rings: {
    id: 'flight_rings',
    label: 'Rooftop Delivery',
    difficultyLevel: 6,
    gateColors: { primary: 0xf59e0b, secondary: 0xec4899, final: 0x22c55e },
    sky: { top: '#f59e0b', mid: '#fbbf24', horizon: '#fde68a', fog: '#d4a574', near: 70, far: 200 },
    vista: { type: 'city_grid', y: -38 },
    hero: { type: 'skyline_tower', t: 0.88 },
    spline: { kind: 'rooftop_stops', length: 195, yRange: [26, 34], stops: 3, count: 16 },
    gates: { mode: 'ring', count: 6, tier: 'standard' },
    gltfTrack: 'neon_metro_01',
    hoverPads: 3,
  },
  jet_stunt: {
    id: 'jet_stunt',
    label: 'Photo Sweep',
    difficultyLevel: 7,
    gateColors: { primary: 0xfb923c, secondary: 0xf8fafc, final: 0xef4444 },
    goldenHour: true,
    sky: { preset: 'sunset_cove_01', top: '#4a90d9', mid: '#ffaa55', horizon: '#ffd966', fog: '#ffcc88', near: 80, far: 240 },
    vista: { type: 'coastline', y: -44 },
    hero: { type: 'lighthouse', t: 0.35 },
    spline: { kind: 'coast_arc', length: 230, yRange: [18, 28], count: 14 },
    gates: { mode: 'ring', count: 6, tier: 'forgiving' },
    gltfTrack: 'sunset_cove_01',
    parallaxClouds: true,
  },
  rooftop_delivery: {
    id: 'rooftop_delivery',
    label: 'Wind Tunnel',
    difficultyLevel: 8,
    gateColors: { primary: 0x14b8a6, secondary: 0xa3e635, final: 0xfacc15 },
    sky: { top: '#0e7490', mid: '#14b8a6', horizon: '#99f6e4', fog: '#5eead4', near: 55, far: 180 },
    vista: { type: 'mountain_pass', y: -50 },
    hero: { type: 'wind_turbines', t: 0.05 },
    spline: { kind: 'wind_tunnel', length: 175, y: 22, count: 14 },
    gates: { mode: 'ring', count: 8, tier: 'hard' },
    gltfTrack: 'frost_peak_01',
    tunnel: true,
    windZones: 3,
  },
  typhoon: {
    id: 'typhoon',
    label: 'Propeller Flip',
    difficultyLevel: 9,
    gateColors: { primary: 0x60a5fa, secondary: 0xf43f5e, final: 0xfde047 },
    sky: { top: '#0f172a', mid: '#1e293b', horizon: '#334155', fog: '#1e293b', near: 45, far: 160 },
    vista: { type: 'ocean_churn', y: -46 },
    hero: { type: 'eye_stunt_ring', t: 0.72 },
    spline: { kind: 'storm_eye', length: 155, y: 24, count: 12 },
    gates: { mode: 'mixed', ringCount: 7, stuntRing: true, tier: 'hard' },
    gltfTrack: 'thunder_ridge_01',
    stormWall: true,
    rain: true,
  },
  warp_gate: {
    id: 'warp_gate',
    label: 'Sky Ace',
    difficultyLevel: 10,
    gateColors: { primary: 0xa855f7, secondary: 0xf97316, final: 0xffffff },
    sky: { preset: 'star_station_01', top: '#120428', mid: '#4a3080', horizon: '#f97316', fog: '#2a1058', near: 70, far: 260 },
    vista: { type: 'planet_curve', y: -55 },
    hero: { type: 'warp_cathedral', t: 0.94 },
    spline: { kind: 'capstone_sections', length: 280, count: 24 },
    gates: { mode: 'ring', count: 14, tier: 'mixed' },
    gltfTrack: 'star_station_01',
    sections: true,
  },
  rainbow_road: {
    id: 'rainbow_road',
    label: 'FPV Prism Circuit',
    difficultyLevel: 1,
    gateColors: { primary: 0xec4899, secondary: 0x06b6d4, final: 0x22c55e },
    sky: { preset: 'star_station_01', top: '#120428', mid: '#2a1058', horizon: '#4c1d95', fog: '#1e1b4b', near: 90, far: 300 },
    vista: { type: 'planet_curve', y: -80 },
    hero: { type: 'warp_cathedral', t: 0.9 },
    spline: { kind: 'figure8', length: 220, centerY: 24, amplitude: 7, count: 24 },
    gates: { mode: 'ring', count: 8, tier: 'tutorial' },
    gltfTrack: 'star_station_01',
    raceRibbon: { colors: [0xec4899, 0x06b6d4, 0xa855f7, 0xfacc15], width: 6, boosts: 4 },
  },
  sunny_circuit: {
    id: 'sunny_circuit',
    label: 'Proximity Drift Circuit',
    difficultyLevel: 3,
    gateColors: { primary: 0x38bdf8, secondary: 0xec4899, final: 0x22c55e },
    goldenHour: true,
    sky: { top: '#38bdf8', mid: '#87ceeb', horizon: '#ffe8b0', fog: '#dbeafe', near: 100, far: 300 },
    vista: { type: 'cloud_sea', y: -52 },
    hero: { type: 'sky_academy_arch', t: 0.08 },
    spline: { kind: 'figure8', length: 200, centerY: 24, amplitude: 5, count: 22 },
    gates: { mode: 'ring', count: 12, tier: 'standard' },
    gltfTrack: 'cloud_citadel_01',
    parallaxClouds: true,
    raceRibbon: { colors: [0xfbbf24, 0x38bdf8, 0xec4899], width: 8, boosts: 3 },
  },
  dragon_skyway: {
    id: 'dragon_skyway',
    label: 'Dragon Spine Slalom',
    difficultyLevel: 5,
    gateColors: { primary: 0xf97316, secondary: 0xa855f7, final: 0x22c55e },
    sky: { top: '#120428', mid: '#4c1d95', horizon: '#f97316', fog: '#2a1058', near: 65, far: 220 },
    vista: { type: 'canyon_floor', y: -50 },
    hero: { type: 'warp_cathedral', t: 0.92 },
    spline: { kind: 'canyon_slalom', length: 240, start: [0, 24, 0], end: [0, 26, -240], yMin: 20, yMax: 30, count: 28 },
    gates: { mode: 'ring', count: 16, tier: 'hard' },
    gltfTrack: 'neon_metro_01',
    tunnel: true,
    raceRibbon: { colors: [0xf97316, 0xa855f7, 0x06b6d4], width: 6, boosts: 6 },
  },
  volcano_drift: {
    id: 'volcano_drift',
    label: 'Volcano Roll Run',
    difficultyLevel: 7,
    gateColors: { primary: 0xa855f7, secondary: 0xf97316, final: 0x22c55e },
    sky: { top: '#0f172a', mid: '#1e1b4b', horizon: '#7f1d1d', fog: '#3f1d2e', near: 50, far: 180 },
    vista: { type: 'lava_sea', y: -45 },
    hero: { type: 'eye_stunt_ring', t: 0.72 },
    spline: { kind: 'storm_eye', length: 180, y: 22, count: 20 },
    gates: { mode: 'mixed', ringCount: 7, stuntRing: true, tier: 'hard' },
    gltfTrack: 'lava_foundry_01',
    raceRibbon: { colors: [0xdc2626, 0xf97316, 0xa855f7], width: 6, boosts: 3 },
  },
  street_grand_prix: {
    id: 'street_grand_prix',
    label: 'Rooftop Skimmer',
    difficultyLevel: 9,
    gateColors: { primary: 0xf59e0b, secondary: 0x22c55e, final: 0x22c55e },
    sky: { top: '#1e293b', mid: '#475569', horizon: '#f59e0b', fog: '#64748b', near: 55, far: 180 },
    vista: { type: 'city_grid', y: -38 },
    hero: { type: 'skyline_tower', t: 0.88 },
    spline: { kind: 'rooftop_stops', length: 200, yRange: [18, 23], stops: 4, count: 24 },
    gates: { mode: 'ring', count: 6, tier: 'hard' },
    gltfTrack: 'neon_metro_01',
    raceRibbon: { colors: [0x64748b, 0xf59e0b, 0x22c55e], width: 5, boosts: 2 },
  },
};

export function getAerialRecipe(arenaType) {
  return AERIAL_COURSE_RECIPES[arenaType] || AERIAL_COURSE_RECIPES.drone_canyon;
}

export function isAerialArenaType(arenaType) {
  return AERIAL_ARENA_TYPES.has(arenaType);
}
