"""
Stub for BBC micro:bit v2 MicroPython `bluetooth` (BLE).

The real module exists only on the device. This file exists so Pylance / Pyright
in VS Code and Cursor stop reporting "Module bluetooth could not be resolved".
"""

from typing import Any, Callable, Optional, Union

class UUID:
    def __init__(self, value: Union[str, int, bytes] = ...) -> None: ...

class BLE:
    def __init__(self) -> None: ...
    def active(self, active: Optional[bool] = None) -> bool: ...
    def config(self, *args: Any, **kwargs: Any) -> Any: ...
    def irq(self, handler: Optional[Callable[..., None]] = None) -> None: ...
    def gatts_register_services(self, services: Any) -> Any: ...
    def gap_advertise(self, interval_us: int, adv_data: Optional[bytes] = None, *args: Any, **kwargs: Any) -> None: ...
    def gatts_notify(self, conn_handle: int, value_handle: int, data: Optional[bytes] = None) -> None: ...
    def gatts_read(self, value_handle: int) -> bytes: ...
