/**
 * CodeRacer minimal HUD configuration — 95% track view, <5% UI overlay.
 */
export const CODERACER_HUD_CONFIG = {
  lapDisplay: {
    position: 'top-left',
    offset: [20, 20],
    fontSize: '12px',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    textColor: '#FFFFFF',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    padding: [8, 12],
    borderRadius: '8px',
    visible: true,
    alwaysShow: true,
  },
  timerDisplay: {
    position: 'top-left',
    offset: [20, 60],
    fontSize: '14px',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    textColor: '#00FF88',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    padding: [8, 12],
    borderRadius: '8px',
    format: 'MM:SS.ms',
  },
  positionDisplay: {
    position: 'top-left',
    offset: [20, 100],
    fontSize: '12px',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    textColor: '#FFFFFF',
    content: '1st place',
  },
  speedGauge: {
    position: 'bottom-right',
    offset: [30, 30],
    size: 60,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    dialColor: '#FFD700',
    borderColor: '#FFFFFF',
    borderWidth: '2px',
    borderRadius: '50%',
    opacity: 0.7,
    visible: true,
  },
  powerUpInventory: {
    position: 'bottom-right',
    offset: [30, 120],
    iconSize: 20,
    spacing: 5,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    padding: [4, 8],
    borderRadius: '4px',
    maxVisible: 3,
    opacity: 0.8,
  },
  notificationCenter: {
    position: 'center',
    fontSize: '18px',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    textColor: '#FFFFFF',
    displayTime: 1000,
    fadeOutTime: 300,
    borderRadius: '12px',
    padding: [16, 24],
    visible: false,
    events: [
      'checkpoint_reached',
      'boost_activated',
      'mission_complete',
      'collision',
      'shortcut_taken',
      'lap_complete',
    ],
    messages: {
      checkpoint_reached: 'Checkpoint! 🎉',
      boost_activated: 'Boost active! 🚀',
      mission_complete: 'Mission complete! ⭐',
      collision: 'Collision! 💥',
      shortcut_taken: 'Shortcut taken! ⚡',
      lap_complete: 'Lap complete! 🏁',
    },
  },
  blockPalette: {
    position: 'hidden-left',
    width: 280,
    triggerKey: 'Escape',
    slideOutTime: 300,
    visible: false,
    backgroundColor: 'rgba(20, 20, 40, 0.95)',
  },
  missionsPanel: {
    position: 'hidden-right',
    width: 300,
    triggerKey: 'Tab',
    slideOutTime: 300,
    backgroundColor: 'rgba(20, 20, 40, 0.95)',
    textColor: '#FFFFFF',
  },
};

export default CODERACER_HUD_CONFIG;
